hibernate:
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/serrano
    password: ''
    username: ''
  dialect: org.hibernate.dialect.PostgreSQLDialect
serrano:
  connection:
    inicio-jdbc: jdbc:postgresql://
  view:
      folder: ${user.dir}/view/
  date:
    pattern: yyyy-MM-dd HH:mm:ss
  secretKey: d5ef2c82-8828-4d3d-9bdb-c2984c46b75c
  log:
    exception: true
  dba:
    cliente:
      folder: dba/cliente
    interno:
      folder: dba/interno
    proxy:
      path: dba/pql
  seguranca:
    preference-path: serrano/user/preferences
  version: '@project.version'
server:
  port: 37777

